#!/usr/bin/env python3
"""
Web Claw Output Structure Validator

Checks that a Web Claw project workspace contains all required deliverables
and that no required file is empty. Adapted from the Version A check_output_structure.py,
updated for the v3 folder layout (blueprint/, research/, decisions/, memory.md).

Usage:
    python check-output.py --workspace <project-dir>
    python check-output.py --workspace ./meridian --json
    python check-output.py --workspace ./meridian --phase blueprint
    python check-output.py --workspace ./meridian --phase all

Exit code: 0 = all required files present and non-empty. 1 = failures found.
"""

from __future__ import annotations

import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _console import safe_stdout
safe_stdout()

import argparse
import json
from pathlib import Path


# -- Required by phase --------------------------------------------------------

PHASE_REQUIREMENTS: dict[str, list[str]] = {
    "bootstrap": [
        "memory.md",
        "blueprint/discovery.md",
        "site-brief.json",
        "dependencies.json",
        "sources.json",
        "qa/qa-plan.md",
    ],
    "blueprint": [
        "memory.md",
        "blueprint/discovery.md",
        "blueprint/sitemap.md",
        "blueprint/style-guide.md",
        "blueprint/wireframes.md",
        "blueprint/animations.md",
    ],
    "research": [
        "memory.md",
        "research/awwwards-references.md",
        "research/youtube-techniques.md",
        "research/tech-stack.md",
        "sources.json",
        "dependencies.json",
    ],
    "execution": [
        "memory.md",
        "plan.md",
        "phase-1.md",
        "phase-2.md",
        "phase-3.md",
    ],
    "qa": [
        "memory.md",
        "qa/qa-plan.md",
        "qa/phase-1-report.md",
        "qa/phase-2-report.md",
        "qa/phase-3-report.md",
    ],
    # Visual quality artifacts produced during phases 2 and 3 + pre-launch.
    # Required for projects that ran the visual-critique-rubric (recommended).
    "visual": [
        "memory.md",
        "qa/visual-critique-phase-2.md",
        "qa/visual-critique-phase-3.md",
    ],
}

# "all" is the union of all phases
PHASE_REQUIREMENTS["all"] = sorted(
    {path for paths in PHASE_REQUIREMENTS.values() for path in paths}
)

# Optional files (not failures if missing, noted in output)
OPTIONAL_PATHS = [
    "decisions/",
    "assets/.gitkeep",
    # Phase 3 / pre-launch additions (logged when missing, not gated):
    "assets/og/",                # generated by scripts/generate-og.py
    "qa/snapshots/",             # baseline screenshots for visual-regression.py
    "design/tokens.json",        # emitted by scripts/extract-tokens.py
]


def nonempty(path: Path) -> bool:
    return path.exists() and path.is_file() and path.stat().st_size > 0


def check_decisions_folder(workspace: Path) -> list[str]:
    """Return a list of decision file paths found in decisions/."""
    decisions_dir = workspace / "decisions"
    if not decisions_dir.is_dir():
        return []
    return sorted(str(p.relative_to(workspace)) for p in decisions_dir.glob("*.md"))


def memory_phase(workspace: Path) -> str | None:
    """Extract the current Phase from memory.md if it exists."""
    memory = workspace / "memory.md"
    if not memory.exists():
        return None
    for line in memory.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("- Phase:"):
            return stripped.split(":", 1)[1].strip()
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workspace", required=True, help="Web Claw project workspace directory.")
    parser.add_argument(
        "--phase",
        choices=list(PHASE_REQUIREMENTS.keys()),
        default="all",
        help="Which phase to check. Default: all.",
    )
    parser.add_argument("--json", action="store_true", dest="json_output", help="Emit machine-readable JSON.")
    args = parser.parse_args()

    workspace = Path(args.workspace).expanduser().resolve()

    if not workspace.is_dir():
        msg = f"Workspace not found: {workspace}"
        if args.json_output:
            print(json.dumps({"error": msg, "ok": False}, indent=2))
        else:
            print(f"ERROR: {msg}")
        return 1

    required = PHASE_REQUIREMENTS[args.phase]
    missing: list[str] = []
    empty: list[str] = []

    for rel in required:
        path = workspace / rel
        if not path.exists():
            missing.append(rel)
        elif path.is_file() and path.stat().st_size == 0:
            empty.append(rel)

    # Memory state
    current_phase = memory_phase(workspace)
    decision_files = check_decisions_folder(workspace)

    # Optional artifact presence (recommended but not gated).
    optional_status: dict[str, bool] = {}
    for rel in OPTIONAL_PATHS:
        p = workspace / rel
        # Trailing-slash entries are directories.
        if rel.endswith("/"):
            optional_status[rel] = p.is_dir() and any(p.iterdir())
        else:
            optional_status[rel] = p.exists() and (
                p.is_dir() or (p.is_file() and p.stat().st_size > 0)
            )

    ok = not missing and not empty
    result = {
        "workspace": str(workspace),
        "checked_phase": args.phase,
        "memory_phase": current_phase,
        "ok": ok,
        "missing": missing,
        "empty": empty,
        "decision_files": decision_files,
        "decision_count": len(decision_files),
        "optional": optional_status,
    }

    if args.json_output:
        print(json.dumps(result, indent=2))
        return 0 if ok else 1

    # Human-readable output
    print(f"Workspace : {workspace}")
    print(f"Phase     : {args.phase}")
    print(f"Memory    : {current_phase or '(memory.md not found or Phase not set)'}")
    print(f"Decisions : {len(decision_files)} file(s) in decisions/")
    print()

    if ok:
        print(f"[OK]   All required files for phase '{args.phase}' are present and non-empty.")
    else:
        if missing:
            print(f"[FAIL] Missing ({len(missing)} file(s)):")
            for item in missing:
                print(f"     - {item}")
        if empty:
            print(f"[WARN] Empty ({len(empty)} file(s) -- exist but have 0 bytes):")
            for item in empty:
                print(f"     - {item}")

    if decision_files:
        print(f"\nDecision files:")
        for d in decision_files:
            print(f"   - {d}")

    # Optional artifacts (informational; not gated).
    missing_optional = [rel for rel, present in optional_status.items() if not present]
    if missing_optional:
        print(f"\nOptional (recommended) artifacts not present:")
        for rel in missing_optional:
            print(f"   - {rel}")

    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
